## Import settings from fastapi_settings.toml file
extends = ["fastapi.toml"]

[default]

env = "prod"
container_env = false
log_level = "INFO"
feed_url = "https://rpilocator.com/feed/"
cache_conf = { directory = ".cache", timeout = 30, expire = 5 }

db_type = "sqlite"
db_host = ""
db_username = ""
db_port = ""
db_database = ".db/demo.sqlite"

[dev]

env = "dev"
log_level = "DEBUG"
test_var = "[Dev] Test Value"
cache_conf = { directory = ".cache.dev", timeout = 30, expire = 5 }

db_type = "sqlite"
db_host = ""
db_username = ""
db_port = ""
db_database = ".db/db.dev.sqlite"

[prod]

test_var = "[Prod] Test Value"
cache_conf = { directory = ".cache", timeout = 30, expire = 300 }

db_type = "sqlite"
db_host = ""
db_username = ""
db_port = ""
db_database = ".db/db.sqlite"
