"""${commit_msg}.

Revision ID: 7c149b3e48f7
Revises: fe3399b0f32e
Create Date: 2023-09-09 02:42:01.342618

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c149b3e48f7"
down_revision: Union[str, None] = "fe3399b0f32e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rpilocator_author", table_name="rpilocator")
    op.drop_index("ix_rpilocator_id", table_name="rpilocator")
    op.drop_index("ix_rpilocator_title", table_name="rpilocator")
    op.drop_table("rpilocator")
    op.drop_index("ix_titleDetail_id", table_name="titleDetail")
    op.drop_index("ix_titleDetail_type", table_name="titleDetail")
    op.drop_table("titleDetail")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titleDetail",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("type", sa.VARCHAR(), nullable=True),
        sa.Column("language", sa.VARCHAR(), nullable=True),
        sa.Column("base", sa.VARCHAR(), nullable=True),
        sa.Column("value", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_titleDetail_type", "titleDetail", ["type"], unique=False)
    op.create_index("ix_titleDetail_id", "titleDetail", ["id"], unique=False)
    op.create_table(
        "rpilocator",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("published", sa.DATETIME(), nullable=True),
        sa.Column("entry_id", sa.VARCHAR(), nullable=True),
        sa.Column("title", sa.VARCHAR(), nullable=True),
        sa.Column("summary", sa.VARCHAR(), nullable=True),
        sa.Column("author", sa.VARCHAR(), nullable=True),
        sa.Column("link", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rpilocator_title", "rpilocator", ["title"], unique=False)
    op.create_index("ix_rpilocator_id", "rpilocator", ["id"], unique=False)
    op.create_index("ix_rpilocator_author", "rpilocator", ["author"], unique=False)
    # ### end Alembic commands ###
