"""${commit_msg}

Revision ID: e83a63107436
Revises: 40608f77da7c
Create Date: 2023-09-09 00:51:59.986430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83a63107436'
down_revision: Union[str, None] = '40608f77da7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rpilocator_author', table_name='rpilocator')
    op.drop_index('ix_rpilocator_id', table_name='rpilocator')
    op.drop_index('ix_rpilocator_title', table_name='rpilocator')
    op.drop_table('rpilocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpilocator',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('entry_id', sa.VARCHAR(), nullable=True),
    sa.Column('published', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rpilocator_title', 'rpilocator', ['title'], unique=False)
    op.create_index('ix_rpilocator_id', 'rpilocator', ['id'], unique=False)
    op.create_index('ix_rpilocator_author', 'rpilocator', ['author'], unique=False)
    # ### end Alembic commands ###
