"""${commit_msg}

Revision ID: f377b20f368e
Revises: 8c24e66bf181
Create Date: 2023-09-09 02:48:26.240088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f377b20f368e'
down_revision: Union[str, None] = '8c24e66bf181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titleDetail_id', table_name='titleDetail')
    op.drop_index('ix_titleDetail_type', table_name='titleDetail')
    op.drop_table('titleDetail')
    op.drop_index('ix_rpiLocator_author', table_name='rpiLocator')
    op.drop_index('ix_rpiLocator_id', table_name='rpiLocator')
    op.drop_index('ix_rpiLocator_title', table_name='rpiLocator')
    op.drop_table('rpiLocator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpiLocator',
    sa.Column('published', sa.DATETIME(), nullable=True),
    sa.Column('entry_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('summary', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('link', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rpiLocator_title', 'rpiLocator', ['title'], unique=False)
    op.create_index('ix_rpiLocator_id', 'rpiLocator', ['id'], unique=False)
    op.create_index('ix_rpiLocator_author', 'rpiLocator', ['author'], unique=False)
    op.create_table('titleDetail',
    sa.Column('entry_id', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('base', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['rpiLocator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_titleDetail_type', 'titleDetail', ['type'], unique=False)
    op.create_index('ix_titleDetail_id', 'titleDetail', ['id'], unique=False)
    # ### end Alembic commands ###
